[package]
name = "pingky"
version = "0.1.0"
edition = "2024"

[profile.dev]
incremental = true
package = {"*" = {opt-level = 3}}

[profile.release]
lto = true
codegen-units = 1

[dependencies]
iced = "0.13.1"
